apiVersion: v1
kind: Service
metadata: 
   name: nginx-service-lb
   labels:
    app: nginx-app
    type: front-end
spec:
  selector:
     app: nginx-app
  type: LoadBalancer
  ports:
   - nodePort: 31000
     port: 80
     targetPort: 80    